### ISSUE TITLE
Report generator

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/NEST-roadmap#11]
[Draft proposal](https://docs.google.com/document/d/1pYdogTA-TNnLec0rBAr1S18HbjPuAvdhzAkNDtgQtZI/edit)

Design:
- [x] https://github.com/insightsengineering/coredev-tasks/issues/116
- [x] https://github.com/insightsengineering/coredev-tasks/issues/123
- [x] insightsengineering/coredev-tasks#132
- [x] insightsengineering/teal#590

Implementation:
* [x] insightsengineering/teal.reporter#12
* [x] insightsengineering/teal.reporter#11
* [x] insightsengineering/teal.reporter#10
* [x] insightsengineering/teal.reporter#9
* [x] insightsengineering/teal.reporter#8
* [x] insightsengineering/teal.reporter#13
* [x] insightsengineering/teal.reporter#14
* [ ] ~~insightsengineering/teal.reporter#15~~
* [x] insightsengineering/teal.reporter#7
* [x] insightsengineering/teal.reporter#6
* [x] insightsengineering/teal.reporter#5
* [x] insightsengineering/teal.reporter#1
* [x] https://github.com/insightsengineering/teal.reporter/issues/45
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/35~~
* [x] insightsengineering/teal#641
* [x]  https://github.com/insightsengineering/teal.reporter/issues/42 (not doing)
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/41~~
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/26~~
* [x] https://github.com/insightsengineering/teal/issues/632
* [ ] ~~https://github.com/insightsengineering/teal.reporter/issues/53~~

Release:
* [x] https://github.com/insightsengineering/idr-tasks/issues/301

Usage:
* [x] https://github.com/insightsengineering/teal.modules.clinical/issues/505
* [x] https://github.com/insightsengineering/teal.modules.clinical/issues/470
* [x] https://github.com/insightsengineering/teal.modules.clinical/issues/506
* [x] https://github.com/insightsengineering/teal.modules.general/issues/386
* [x] https://github.com/insightsengineering/teal.osprey/issues/140
* [x] https://github.com/insightsengineering/teal.goshawk/issues/145
* [x] https://github.com/insightsengineering/teal.modules.hermes/issues/238

Order of Items:
https://miro.com/app/board/uXjVOEnaJfI=/
