### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/NEST-roadmap#12]
The vignettes would get linked within the re-designed user guide insightsengineering/NEST-roadmap-roche#7

- [x] https://github.com/insightsengineering/coredev-tasks/issues/61

README:
- [x] https://github.com/insightsengineering/coredev-tasks/issues/120
- [x] https://github.com/insightsengineering/coredev-tasks/issues/119

"getting started" vignettes:
In order to have it as a "Get started" subpage in pkgdown website, it has to be named from the package name - see [docs](https://pkgdown.r-lib.org/articles/customise.html#:~:text=built%2Din%20components%3A-,intro,-%3A%20%E2%80%9CGet%20Started%E2%80%9D%2C%20which)
- [x] https://github.com/insightsengineering/scda/issues/61
- [x] https://github.com/insightsengineering/tern/issues/333
- [x] https://github.com/insightsengineering/teal/issues/532
- [x] https://github.com/insightsengineering/teal.modules.clinical/issues/379
- [x] https://github.com/insightsengineering/teal.modules.general/issues/347
- [x] https://github.com/insightsengineering/tern.mmrm/issues/16
- [x] https://github.com/insightsengineering/teal.transform/issues/50
- [x] https://github.com/insightsengineering/tern.rbmi/issues/7

VIGNETTE:
Document (create or review or join from agile-R) main features as a vignette (please make sure that individual functions refers to appropriate vignette). It is assumed that this vignette replaces agile-R article (if it's there).

- [x] https://github.com/insightsengineering/teal/issues/517
- [x] insightsengineering/teal.slice#5
- [x] insightsengineering/teal#612
- creating analysis datasets for teal modules
   - [x] insightsengineering/teal.transform#25
   - [x] insightsengineering/teal.transform#26 
- [x] insightsengineering/teal.data#7
- reproducibility
  - [x] insightsengineering/teal.code#2
  - [x] insightsengineering/teal.code#1
- [x] insightsengineering/teal.data#40
- [x] insightsengineering/coredev-tasks#176
- [x] https://github.com/insightsengineering/teal/issues/522
- [x] https://github.com/insightsengineering/teal.transform/issues/49

Landing page:
- [ ] insightsengineering/coredev-tasks#233

Apps in vignettes:
- [ ] The apps do not show up in the static vignette pages - we just get a big white square - we should do something about this (host them somewhere and embed them, remove them and only show the source code etc.)
